function cambiar(){

    let eleccion = document.getElementById("eleccion");
    let text = document.getElementById("main")

    if(eleccion.value == "Chicken")  {
        text.innerHTML = `<div class="border">
        <div class="mt-0 mb-1 bg-alert border h-50 w-50 d-inline-block"><p >Chicken</p></div>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur qui expedita dolorum debitis rerum, est maxime sit ad. Aut tenetur provident eius similique quae praesentium accusamus possimus labore architecto nobis?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non adipisci unde natus, ratione fugit voluptatibus, tempora minus hic vitae laborum ea eum nisi! Debitis odio, placeat nisi at dolorem Lorem ipsum dolor sit, amet consectetur adipisicing elit. Delectus provident nihil quibusdam dolor odio, dolores blanditiis ab! Impedit perspiciatis, magni similique beatae eius corrupti voluptatibus quo officiis officia saepe unde. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere odit at dolor sint ipsam. Excepturi sit fugiat doloribus necessitatibus rerum. Consequatur dolores architecto veritatis velit iure! Unde quam velit et! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minima quas dolores omnis temporibus minus officia dolorem quos quod ipsum voluptatum sit provident maiores, repellat impedit? Beatae et in culpa Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta, neque et aliquid rerum molestiae unde necessitatibus asperiores libero incidunt! Voluptatem officiis dolore praesentium reiciendis distinctio maxime atque non eius eaque.</p>   
    </div>`
    } else if(eleccion.value == "Beef" ){
        text.innerHTML = `<div class="border">
        <div class="mt-0 mb-1 bg-alert border h-50 w-50 d-inline-block"><p >Beef</p></div>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur qui expedita dolorum debitis rerum, est maxime sit ad. Aut tenetur provident eius similique quae praesentium accusamus possimus labore architecto nobis?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non adipisci unde natus, ratione fugit voluptatibus, tempora minus hic vitae laborum ea eum nisi! Debitis odio, placeat nisi at dolorem Lorem ipsum dolor sit, amet consectetur adipisicing elit. Delectus provident nihil quibusdam dolor odio, dolores blanditiis ab! Impedit perspiciatis, magni similique beatae eius corrupti voluptatibus quo officiis officia saepe unde. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere doloremque eius placeat dicta, autem distinctio obcaecati ullam fugit iure in voluptates quis itaque voluptatibus accusantium eveniet sequi provident! Doloribus, quaerat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem eveniet eum optio, quis ex adipisci, tempora dolores odit magni ea pariatur deleniti, iste dolore recusandae hic rem excepturi consequuntur eos. Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus non distinctio, nihil libero veritatis doloremque! Numquam voluptas id ratione corporis, ullam dignissimos doloribus repellendus labore officiis, alias minima nobis odit? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci explicabo at ducimus rerum ab. Rem in, sequi atque, nostrum eaque vero, nam quas veniam voluptates culpa nesciunt libero soluta sapiente! Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit assumenda minus odit dolorem? Obcaecati sed velit molestiae aperiam architecto deserunt, dolore autem iusto iste porro excepturi, optio, ut vel ipsam!</p>   
</div>`
    } else {
        text.innerHTML = `   <div class="border">
        <div class="mt-0 mb-1 bg-alert border h-50 w-50 d-inline-block"><p >Sushi</p></div>
        
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur qui expedita dolorum debitis rerum, est maxime sit ad. Aut tenetur provident eius similique quae praesentium accusamus possimus labore architecto nobis?Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non adipisci unde natus, ratione fugit voluptatibus, tempora minus hic vitae laborum ea eum nisi! Debitis odio, placeat nisi at dolorem Lorem ipsum dolor sit, amet consectetur adipisicing elit. Delectus provident nihil quibusdam dolor odio, dolores blanditiis ab! Impedit perspiciatis, magni similique beatae eius corrupti voluptatibus quo officiis officia saepe unde. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem fuga provident molestias impedit eaque necessitatibus unde doloribus, iure non eveniet magni laboriosam libero ipsa quasi cupiditate hic at ipsum nam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Reiciendis, molestiae beatae, sapiente nisi, perferendis repudiandae libero rerum natus quia consequuntur amet eius aspernatur recusandae quae qui ad cum quibusdam est. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptates libero, minus consectetur qui vero soluta voluptatum, enim tempora animi nemo aperiam. Voluptate dolores magni, rerum quas sed hic debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem nobis quae eum, magnam, quo, quod ducimus tempore consequatur commodi minima doloremque animi cumque nisi harum debitis pariatur illo reiciendis explicabo! Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim minus molestiae quis reiciendis, magnam molestias deleniti sunt consectetur pariatur, repudiandae, necessitatibus fugiat eos cumque at odit assumenda. Quos, quidem provident. </p>   

</div>`
    }

}
